package com.java;

public class TypeCasting {

	public static void main(String[] args) {
		
		//internal type casting
		char a='A';
		int a1=a;
		long a2=a1;
		float a3=a2;
		double a4=a3;
		System.out.println("value generated by internal type casting: ");
		System.out.println("value of char a = "+a);
		System.out.println("value of int a1 from char '"+a+"' = "+a1);
		System.out.println("value of long a2 from int "+a1+" = "+a2);
		System.out.println("value of float a3 from long "+a2+" = "+a3);
		System.out.println("value of double a4 from float "+a3+" = "+a4+"\n\n");

		
		//External type casting
		double b=97;
		float b1=(float)b;
		long b2=(long)b1;
		int b3=(int)b2;
		char b4=(char)b3;
		System.out.println("value generated by external type casting: ");
		System.out.println("value of double b = "+b);
		System.out.println("value of float b1 from double "+b+" = "+b1);
		System.out.println("value of long b2 from float "+b1+" = "+b2);
		System.out.println("value of int b3 from long "+b2+" = "+b3);
		System.out.println("value of char b4 from int "+b3+" = "+b4);

	}

}
